name: garcom_facil
description: MVP de app de garcom com roteamento de pedidos por setor e impressao em rede.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
